"""wtf

Revision ID: 5cd5e42303f2
Revises: b78942501330
Create Date: 2022-11-25 09:50:53.246453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cd5e42303f2'
down_revision = 'b78942501330'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('customer_customer_type_id_fkey', 'customer', type_='foreignkey')
    op.create_foreign_key(None, 'customer', 'customer_type', ['customer_type_id'], ['id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'customer', schema='public', type_='foreignkey')
    op.create_foreign_key('customer_customer_type_id_fkey', 'customer', 'customer_type', ['customer_type_id'], ['id'])
    # ### end Alembic commands ###
