"""create-customer

Revision ID: b78942501330
Revises: da119d71d931
Create Date: 2022-11-25 09:48:23.161620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b78942501330'
down_revision = 'da119d71d931'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('primary_key', sa.String(length=32), nullable=False, comment='UID'),
    sa.Column('first_name', sa.String(length=100), nullable=False, comment='First name'),
    sa.Column('last_name', sa.String(length=100), nullable=False, comment='Last name'),
    sa.Column('customer_type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_type_id'], ['public.customer_type.id'], ),
    sa.PrimaryKeyConstraint('primary_key'),
    schema='public'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customer', schema='public')
    # ### end Alembic commands ###
